globals:
  SystemJS: true
  __moduleName: true
extends:
  - eslint:recommended
  - google
  - prettier
parser: babel-eslint
parserOptions:
  ecmaVersion: 2019
  sourceType: module
  ecmaFeatures:
    jsx: true
rules:
  eol-last:
    - 0
  indent: 0
  generator-star-spacing: off
  no-else-return: 1
  max-len: [error, 120]
  no-console: 0
  no-new: warn
  no-var: error
  no-unused-vars: error
  require-jsdoc: off
  valid-jsdoc: off
  prefer-const: error
env:
  browser: true
  node: true
  es6: true
  jest: true
  jasmine: true
